PetTech/urls.py
from django.contrib import admin
from django.urls import path,include
#from core.views import getProdutos
from core import views
from django.conf import settings
from django.conf.urls.static import static

#from django.conf.urls import url, include
from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets


# Routers provide an easy way of automatically determining the URL conf.
#router = routers.DefaultRouter()
#router.register('getprodutos', getProdutos)

urlpatterns = [
    #path('api/', include(router.urls)),
    path('admin/', admin.site.urls,name="admin"),
    path('registerusers/', views.signup,name="registerusers"),
    path('login/', views.login_user,name="login"),
    path('login/submit', views.submit_login,name="submit"),
    path('logout/', views.logout_user,name="logout"),
    path('', views.index,name="index"),
    path('registerprodutos/',views.produtos,name='registerprodutos'),
    path('registerpedidocompra/',views.pedido_compra,name='registerpedidocompra'),
    path('registerpedidovenda/',views.pedido_venda,name='registerpedidovenda'),
    path('registerclientes/',views.clientes,name='registerclientes'),
    path('clientes/',views.list_clientes,name='clientes'),
    path('clientes/updatecliente/<str:id>',views.updatecliente,name='updatecliente'),
    path('fornecedores/updatefornecedor/<str:id>',views.updatefornecedor,name='updatefornecedor'),
    path('fornecedores/',views.list_fornecedores,name='fornecedores'),
    path('registerfornecedores/',views.fornecedores,name='registerfornecedores'),
    path('registerpagamentos/',views.register_formas,name='registerpagamentos'),
    path('registeragenda/',views.agendamentos,name='registeragenda'),
    path('agendamentos/',views.list_agendamentos,name='agendamentos'),
    path('servicos/',views.list_servicos,name='listservicos'),
    path('registerservicos/',views.servicos,name='registerservicos'),
    path('servicos/servicedel/<str:id_servico>',views.deleteservico,name='deleteservico'),
    path('clientes/details/<str:id_cliente>', views.client_details, name='detailsclientes'),
    path('fornecedores/details/<str:id_fornecedor>', views.forn_details, name='detailsfornecedores'),
    path('consultas/produtos/details/<str:id>', views.prod_details, name='detailsprodutos'),


    # --------------------Urls de pedidos---------------------------------

    # --------------------Urls de consultas---------------------------------
    path('consultas/produtos/',views.list_produtos,name='produtos'),
    path('consultas/produtos/updateproduto/<str:id>',views.updateproduto,name='updateproduto'),
    path('consultas/pedidos/aprovados/details/<str:id_pedido>', views.ped_details_aprovado, name='ped_details_aprovado'),
    path('consultas/pedidos/pendentes/details/<str:id_pedido>', views.ped_details_pendente, name='ped_details_pendente'),
    path('consultas/pedidos/pendentes/efetivar/<str:id>', views.efetivar_pedido, name='efetivar_pedido'),
    path('consultas/pedidos/aprovados/', views.pedidos_aprovados, name='pedidos_aprovados'),
    path('consultas/pedidos/pendentes/', views.pedidos_pendentes, name='pedidos_pendentes'),
    path('consultas/saldos/', views.consultar_saldos, name='consultar_saldos'),
    path('consultas/entradas/', views.consultar_entradas, name='consultar_entradas'),
    path('consultas/saidas/', views.consultar_saidas, name='consultar_saidas'),
    path('agendamentos/details/<str:id_servico>/', views.agendamento_details, name='detailsagendamentos'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Cliente(models.Model):
    #tipo_pessoa = models.CharField(max_length=20)
    tipo_pessoa = models.TextField()
    nome = models.CharField(max_length=200)
    sexo = models.CharField(max_length=20)
    cpf_cnpj = models.CharField(max_length=14)
    rg = models.TextField()
    email = models.EmailField()
    estado_civil = models.CharField(max_length=15)
    data_nasc = models.DateField()
    cep = models.TextField()
    endereco = models.CharField(max_length=200)
    complemento = models.CharField(max_length=100)
    numero = models.CharField(max_length=6)
    cidade = models.CharField(max_length=50)
    bairro = models.CharField(max_length=60)
    estado = models.CharField(max_length=40)
    tipo_tel = models.TextField()
    tel = models.CharField(max_length=12)
    #uuid = models.CharField(default='-- -- --', max_length=300)
    #url = models.URLField(default='-- -- --', max_length=300)

    def save(self, *args, **kwargs):
        
        #Validação do objeto.
        
        TIPO_PESSOA = ['Fisica', 'Juridica']
        SEXO = ['Masculino', 'Feminino']
        ESTADO_CIVIL = [
                        'Solteiro(a)',
                        'Casado(a)',
                        'Divorciado(a)',
                        'Víuvo(a)'
                        ]
        ESTADO = [
                "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
                "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
                "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
                ]
        TIPO_TEL = ['Residencial', 'Celular', 'Comercial']

        if self.tipo_pessoa not in TIPO_PESSOA:
            raise Exception('Campo Tipo Pessoa Inválido!')
        if self.sexo not in SEXO:
            raise Exception('Campo Sexo Inválido!')
        #if self.estado_civil not in ESTADO_CIVIL:
         #   raise Exception('Campo Estado Civil Inválido!')
        if self.estado not in ESTADO:
            raise Exception('Campo Estado Inválido!')
        if self.tipo_tel not in TIPO_TEL:
            raise Exception('Campo Tipo de Telefone Inválido!')
        #self.url = f'/cliente/details/{self.uuid}/'
        super(Cliente, self).save(*args, **kwargs)


class Fornecedor(models.Model):
    tipo_pessoa = models.CharField(max_length=200)
    data_cadastro = models.DateField()
    nome_fantasia = models.CharField(max_length=200)
    razao_social = models.CharField(max_length=200)
    cpf_cnpj = models.CharField(max_length=200)
    rg_ie = models.CharField(max_length=200)
    cep = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200)
    numero = models.CharField(max_length=200)
    cidade = models.CharField(max_length=200)
    bairro = models.CharField(max_length=200)
    estado = models.CharField(max_length=200)
    fax = models.CharField(max_length=200)
    tel = models.CharField(max_length=200)
    email = models.EmailField()
    #uuid = models.CharField(default='-- -- --', max_length=300)
    #url = models.URLField(default='-- -- --', max_length=300)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """
        TIPO_PESSOA = ['Fisica', 'Juridica']
        ESTADO = [
                "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
                "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
                "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
                ]

        if self.tipo_pessoa not in TIPO_PESSOA:
            raise Exception('Campo Inválido!')
        if self.estado not in ESTADO:
            raise Exception('Campo Inválido!')
        #self.url = f'/fornecedor/details/{self.uuid}/'
        super(Fornecedor, self).save(*args, **kwargs)


class Produto(models.Model):
    # id_produto = models.IntegerField()
    cod_bar = models.CharField(max_length=200)
    data_cadastro = models.DateField()
    descricao = models.CharField(max_length=200)
    marca = models.CharField(max_length=200)
    #custo = models.DecimalField(max_digits=12, decimal_places=2)
    #venda = models.DecimalField(max_digits=12, decimal_places=2)
    #lucro = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    #estoque = models.PositiveIntegerField()
    #uuid = models.CharField(default='-- -- --', max_length=300)
    #url = models.URLField(default='-- -- --', max_length=300)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """
        try:
            super(Produto, self).save(*args, **kwargs)
        except e:
            raise(e)

class Agendamentos(models.Model): 
    proprietario = models.CharField(max_length=80)
    animal   = models.CharField(max_length=60)
    telefone = models.CharField(max_length=60)
    email    = models.EmailField()
    
    #Serviços
    #servico = models.CharField(max_length=50,on)
    servico = models.ForeignKey('Servicos',on_delete=models.CASCADE,related_name='servico')
    serv_desc = models.CharField(max_length=50,default="")

    #Agendamento
    data = models.DateField()
    dia  = models.CharField(max_length=10)
    hora = models.CharField(max_length=10)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        dias = {
                "SUNDAY":"DOMINGO",
                "MONDAY":"SEGUNDA", 
                "TUESDAY":"TERCA",
                "WEDNESDAY":"QUARTA",
                "THURSDAY":"QUINTA", 
                "FRIDAY":"SEXTA", 
                "SATURDAY":"SABADO"
                }

        servicos_all = Servicos.objects.all().order_by('-id')  

        if not self.proprietario:
            raise Exception('Campo proprietario invalido !')
        if not self.animal:
            raise Exception('Campo animal invalido !')        
        if not self.telefone:
            raise Exception('Campo telefone invalido !')
        if not self.email:
            raise Exception('Campo e-mail invalido !')   

        if self.servico not in servicos_all:
            raise Exception('Serviço inválido')
        
        self.dia = dias[self.dia.strip().upper()]

        super(Agendamentos, self).save(*args, **kwargs)


class Servicos(models.Model):
    descricao = models.CharField(max_length=50)
    disponivel = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        #produto = Produto.objects.get(id=self.id_produto)
        if not self.descricao:
            raise Exception('Campo descricao precisa ser preenchido !')
            
        super(Servicos, self).save(*args, **kwargs)

class Pedido(models.Model):
    cliente = models.IntegerField()
    cpf_cnpj = models.CharField(max_length=14)
    tipo  = models.CharField(max_length=20) #Venda ou Compra
    emissao = models.DateField(default=timezone.now)
    pagamento = models.ForeignKey('Tipos_pagamento',on_delete=models.CASCADE,) 
    forma_pagamento = models.CharField(max_length=60)
    vendedor  = models.CharField(max_length=150)
    observacao = models.CharField(max_length=200)     
    efetivado = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        clientes = Cliente.objects.all().order_by('-id')  

        #produto = Produto.objects.get(id=self.id_produto)
        if not self.cliente:
            raise Exception('Campo cliente invalido !')

            
        super(Pedido, self).save(*args, **kwargs)

class Itens_pedido(models.Model):
    
    TIPOS = [('P','S')]

    #tipo = models.CharField(max_length=14, choices=TIPOS, blank=False)
    produto = models.ForeignKey('Produto', on_delete=models.CASCADE,)
    descricao = models.CharField(max_length=150, blank=False) 
    quantidade = models.IntegerField()
    valor_unitario = models.DecimalField(max_digits=12, decimal_places=2,blank=False)
    valor_total = models.DecimalField(max_digits=12, decimal_places=2)
    pedido = models.ForeignKey('Pedido',on_delete=models.CASCADE,)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        if not self.valor_unitario:
            raise Exception('Campo valor_unitario invalido !')
        if not self.quantidade:
            raise Exception('Campo quantidade invalido !')
        if not self.valor_total:
            raise Exception('Campo valor_total invalido !')
        super(Itens_pedido, self).save(*args, **kwargs)

class Estoque(models.Model):
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE,related_name='produto')
    quantidade = models.IntegerField()

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        #produto = Produto.objects.get(id=self.id_produto)
        if not self.quantidade:
            raise Exception('Campo quantidade invalido !')
        
        if Produto.objects.get(pk=self.produto_id) == None:
            raise Exception('Produto inválido')
            
        super(Estoque, self).save(*args, **kwargs)


class Entrada(models.Model):
    Pedido = models.ForeignKey(Pedido,on_delete=models.CASCADE,related_name='pedido_entrada')
    fornece = models.ForeignKey(Fornecedor,on_delete=models.CASCADE,related_name='cliente_entrada')
    fornece_nome = models.CharField(max_length=200)
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE,related_name='produto_entrada')
    produto_descricao = models.CharField(max_length=250)
    quantidade = models.IntegerField()
    valor_unitario = models.DecimalField(max_digits=12, decimal_places=2,blank=False)
    valor_total    = models.DecimalField(max_digits=12, decimal_places=2,blank=False)

    def save(self, *args, **kwargs):
        """
        Validação do objeto.
        """

        #produto = Produto.objects.get(id=self.id_produto)
        if not self.quantidade:

core/forms.py
from django import forms
from django.core.mail import EmailMessage

from .models import Cliente, Fornecedor, Produto,Pedido


class ClienteForm(forms.Form):

    tipo_pessoa = forms.CharField(required=True)
    nome = forms.CharField(required=True)
    sexo = forms.CharField()
    cpf_cnpj = forms.CharField(required=True)
    rg = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    estado_civil = forms.CharField(required=True)
    data_nasc = forms.DateField()
    cep = forms.CharField(required=True)
    endereco = forms.CharField(required=True)
    complemento = forms.CharField(required=False)
    numero = forms.CharField(required=True)
    cidade = forms.CharField(required=True)
    bairro = forms.CharField(required=True)
    estado = forms.CharField(required=True)
    tipo_tel = forms.CharField(required=True)
    tel = forms.CharField(required=True)


class FornecedorForm(forms.Form):
    tipo_pessoa = forms.CharField(required=True)
    data_cadastro = forms.DateField(required=True)
    nome_fantasia = forms.CharField(required=True)
    razao_social = forms.CharField(required=True)
    cpf_cnpj = forms.CharField(required=True, min_length=11, max_length=14)
    rg_ie = forms.CharField(required=True, min_length=9, max_length=9 )
    cep = forms.CharField(required=True,min_length=8, max_length=8)
    endereco = forms.CharField(required=True)
    numero = forms.CharField(required=True)
    cidade = forms.CharField(required=True)
    bairro = forms.CharField(required=True)
    estado = forms.CharField(required=True)
    fax = forms.CharField(required=False)
    tel = forms.CharField(required=True, min_length=10, max_length=11)
    email = forms.EmailField(required=True)


class ProdutoForm(forms.Form):
    # id_produto = forms.IntegerField(required=True)
    cod_bar = forms.IntegerField(required=False,min_value=1, max_value=9999999999999)
    data_cadastro = forms.DateField(required=True)
    descricao = forms.CharField(required=True)
    marca = forms.CharField(required=True)


class PedidoForm(forms.Form):
    cliente = forms.IntegerField()
    pagamento = forms.CharField(max_length=20,required=True)
    vendedor  = forms.CharField(max_length=150,required=True)
    observacao = forms.CharField(max_length=200,required=False) 
    tipo    = forms.CharField(required=True) 

class AgendamentoForm(forms.Form):
    dono = forms.CharField(required=True)
    pet = forms.CharField(required=True)
    data = forms.DateField(required=True)
    hora = forms.TimeField(required=True)
    servico = forms.CharField(required=True)

core/templates/update/fornecedores.html
{% extends "base.html" %} {% block titulo %} Fornecedores {% endblock %} {% block content %}
<h2 class="h2 d-flex justify-content-center">{{ titulo}}</h2>
<br />
<br />
<div class="h-100 d-flex justify-content-center align-items-center">
  <form action="" method="POST" class="text-primary">
    {% csrf_token %}
    <div class="form-row">
      <div class="col-9">
        <label>Nome Fantasia \ Nome Reduzido</label>
        <input type="text" name="nome_fantasia" value="{{ fornecedor.nome_fantasia }}" class="form-control" placeholder="Nome Fantasia" />
      </div>
      <div class="form-group col">
        <label for="tipo_pessoa">Tipo Pessoa</label>
        <input type="text" name="tipo_pessoa" value="{{ fornecedor.tipo_pessoa }}" id="id_tipo_pessoa" class="form-control" readonly/>
      </div>
    </div>
    <div class="form-row">
      <div class="alert alert-danger col-9">
        {% if form.nome_fantasia.errors %}
        <strong>{{ form.nome_fantasia.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-3">
        {% if form.tipo_pessoa.errors %}
        <strong>{{ form.tipo_pessoa.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <div class="col-9">
        <label>Razão Social \ Nome Completo</label>
        <input type="text" name="razao_social"  value="{{ fornecedor.razao_social }}" class="form-control" placeholder="Razão Social" />
      </div>
      <div class="form-group">
        <label>Data Cadastro</label>
        <input
          type="date"
          name="data_cadastro"
          value="{{ fornecedor.data_cadastro }}"
          max="3000-12-31"
          min="1000-01-01"
          class="form-control"
          readonly
        />
      </div>
    </div>

    <div class="form-row">
      <div class="alert alert-danger col-9">
        {% if form.razao_social.errors %}
        <strong>{{ form.razao_social.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-3">
        {% if form.data_cadastro.errors %}
        <strong>{{ form.data_cadastro.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <div class="col-6">
        <label>CPF/CNPJ</label>
        <input type="text" name="cpf_cnpj"  value="{{ fornecedor.cpf_cnpj }}" class="form-control" placeholder="CPF/CNPJ" readonly/>
      </div>
      <div class="col-6">
        <label>RG/IE</label>
        <input type="text" name="rg_ie"  value="{{ fornecedor.rg_ie }}" class="form-control" placeholder="RG/IE" />
      </div>
    </div>

    <div class="form-row">
      <div class="alert alert-danger col-6">
        {% if form.cpf_cnpj.errors %}
        <strong>{{ form.cpf_cnpj.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-6">
        {% if form.rg_ie.errors %}
        <strong>{{ form.rg_ie.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <div class="col-2">
        <label>CEP</label>
        <input type="number" name="cep"  value="{{ fornecedor.cep }}" class="form-control" placeholder="CEP" />
      </div>
      <div class="col-10">
        <label>Endereço</label>
        <input type="text" name="endereco"  value="{{ fornecedor.endereco }}" class="form-control" placeholder="Endereço" />
      </div>
    </div>

    <div class="form-row">
      <div class="alert alert-danger col-2">
        {% if form.cep.errors %}
        <strong>{{ form.cep.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-10">
        {% if form.endereco.errors %}
        <strong>{{ form.endereco.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <div class="col-2">
        <label>Número</label>
        <input type="number" name="numero"  value="{{ fornecedor.numero }}" class="form-control" placeholder="Número" />
      </div>

      <div class="col-4">
        <label>Bairro</label>
        <input type="text" name="bairro"  value="{{ fornecedor.bairro }}" class="form-control" placeholder="Bairro" />
      </div>
      <div class="col-4">
        <label>Cidade</label>
        <input type="text" name="cidade"  value="{{ fornecedor.cidade }}" class="form-control" placeholder="Cidade" />
      </div>
      <div class="form-group col">
        <label for="state">Estado</label>
          <input type="text" name="estado" value="{{ fornecedor.estado }}" id="estado" class="form-control" readonly/>
      </div>
    </div>

    <div class="form-row">
      <div class="alert alert-danger col-2">
        {% if form.numero.errors %}
        <strong>{{ form.numero.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.bairro.errors %}
        <strong>{{ form.bairro.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.cidade.errors %}
        <strong>{{ form.cidade.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-2">
        {% if form.estado.errors %}
        <strong>{{ form.estado.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <div class="col-4">
        <label>Telefone</label>
        <input type="number" name="tel"  value="{{ fornecedor.tel }}" class="form-control" placeholder="ex: (99)9999-9999" />
      </div>
      <div class="col-4">
        <label>Fax</label>
        <input type="tel" name="fax"  value="{{ fornecedor.fax }}" class="form-control" placeholder="Fax" />
      </div>
      <div class="col-4">
        <label>E-mail</label>
        <input type="email" name="email"  value="{{ fornecedor.email }}" class="form-control" placeholder="E-mail" />
      </div>
    </div>

    <div class="form-row">
      <div class="alert alert-danger col-4">
        {% if form.tel.errors %}
        <strong>{{ form.tel.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.fax.errors %}
        <strong>{{ form.fax.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.email.errors %}
        <strong>{{ form.email.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>

    <br />
    <br />
    <center class="text-danger">
      <h5>{{ erro }}</h5>
    </center>
    <div class="d-flex justify-content-around">
      <div class="col-5">
        <a href="/fornecedores/">
          <button type="button" class="btn btn-outline-danger col-12">Cancelar</button>
        </a>
      </div>
      <button type="submit" class="btn btn-outline-primary col-5">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

core/templates/update/produtos.html
{% extends "base.html" %} 
{% block titulo %} 
  {{ titulo }} 
{% endblock %}
{% block content %}
<h2 class="h2 d-flex justify-content-center">Atualizar produto</h2>
<br />
<br />
<div class="h-100 d-flex justify-content-center align-items-center">
  <form action="" method="POST" class="text-primary">
    {% csrf_token %}
    <div class="form-row">
      <div class="col-8">
        <label>Código de Barras</label>
        <input
          type="number"
          name="cod_bar"
          class="form-control"
          placeholder="EAN-13"
          maxlength="13"
          value="%{{ produto.cod_bar }}%"
        />
      </div>
      <div class="form-group col-4">
        <label>Data Cadastro</label>
        <input
          type="date"
          name="data_cadastro"
          max="3000-12-31"
          min="1000-01-01"
          class="form-control"
          value="{{ produto.data_cadastro }}"
        />
      </div>
    </div>
    <div class="form-row">
      <div class="alert alert-danger col-8">
        {% if form.cod_bar.errors %}
        <strong>{{ form.cod_bar.errors | escape }}</strong>
        {% endif %}
      </div>
      <!-- </div>
    <div class="form-row"> -->
      {% if form.data_cadastro.errors %}
      <div class="alert alert-danger col-4">
        <strong>{{ form.data_cadastro.errors | escape }}</strong>
      </div>
      {% endif %}
    </div>
    <div class="form-row">
      <div class="col-12">
        <label>Descrição</label>
        <input
          type="text"
          name="descricao"
          class="form-control"
          placeholder="Descrição"
          value="{{ produto.descricao }}"
        />
      </div>
    </div>
    <div class="form-row">
      {% if form.descricao.errors %}
      <div class="alert alert-danger col-12">
        <strong>{{ form.descricao.errors | escape }}</strong>
      </div>
      {% endif %}
    </div>
    <div class="form-row">
      <div class="col-12">
        <label>Marca</label>
        <input
          type="text"
          name="marca"
          class="form-control"
          placeholder="Marca"
          value="{{ produto.marca }}"
        />
      </div>
    </div>
    <div class="form-row">
      {% if form.marca.errors %}
      <div class="alert alert-danger col-12">
        <strong>{{ form.marca.errors | escape }}</strong>
      </div>
      {% endif %}
    </div>
    <div class="form-row">
      <div class="alert alert-danger col-4">
        {% if form.custo.errors %}
        <strong>{{ form.custo.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.venda.errors %}
        <strong>{{ form.venda.errors | escape }}</strong>
        {% endif %}
      </div>
      <div class="alert alert-danger col-4">
        {% if form.estoque.errors %}
        <strong>{{ form.estoque.errors | escape }}</strong>
        {% endif %}
      </div>
    </div>
    <br />
    <br />
    <center class="text-danger">
      {% if erro  %}
      <h5>{{ erro }}</h5>
      {% endif %}
    </center>
    <div class="d-flex justify-content-around">
      <div class="col-5">
        <a href="consultas/produtos/">
          <button type="button" class="btn btn-outline-danger col-12">Cancelar</button>
        </a>
      </div>
      <button type="submit" class="btn btn-outline-primary col-5">Cadastrar</button>
    </div>
  </form>
</div>
{% endblock %}